# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5d0390f29cfa3f6081e1c9fb31f49c40f64986c2a10236c1fbd4d8b23c88385ae12927ed04389b281797f51145edbececb6f93dbe2c83b9dc931a530027f46a

test:
  secret_key_base: 596b4c0762cbbf7d7701c9a7ae9ffae76abf54ee0b4d2ba194cbc3637edbe4e0814d4ebade111e121d083157ad0fed486a60ce0a3230182d2bd3d2d8fed887b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
